### ISSUE TITLE
doc for building boxes?

### ISSUE THREAD

**Issue by mkinney** [lavabit/robox#108]
Is there a getting started doc or some examples on how to build a box?

For instance, I'm on a mac and would like to build one of the boxes. What would the command look like: "./robox.sh vmware alpine310"?

When I run that, I get:

`Failed to initialize build 'generic-debian10-vmware': error initializing builder 'vmware-iso': pipe: too many open files`

Is the "robox.sh" command intended to run only on linux?

**Comment by timschumi** [comment]
As outlined on [the wiki](https://github.com/lavabit/robox/wiki), the usual command to build a single box is `./robox.sh box generic-<target>-<hypervisor>`. For your configuration, that command would be `./robox.sh box generic-alpine310-vmware`.

Whether the issue you hit is related to the wrong command or due to building on a Mac I don't know, but you should probably try again with the correct command.

**Comment by ladar** [comment]
It might be worth noting that I only build Parallels boxes on MacOS. You might run into various issues with the scripts/configs because MacOS (aka BSD) uses different commands/syntax etc, so your mileage may vary. If you find an issue, and know how to fix it, please submit a pull request with the fix.

When you run `robox.sh` for the first time, it will create a `.credentialsrc` file using a generic template. Once you have that file you could, in theory, bypass the `robox.sh` script by running:

```
source .credentialsrc
packer build -only=generic-alpine310-vmware generic-vmware.json
```

As for the specific error you posted above, with too many open files, I recently encountered that error while trying to validate the `generic-hyperv.json` file using `packer` version 1.5.5. It worked fine using version 1.4.5 which is what my build bots currently have installed. 

I haven't had time to investigate/report this issue upstream yet. Also note that packer version 1.5.5 found a few minor JSON issues (duplicate keys, renaming `ssh_wait_timeout` to `ssh_timeout`, etc) that I wasn't able to fix because of that open file bug.

If you want to play the VMWare images specifically, there is a script in `res/providers/provider.sh` which you can use to setup/configure a CentOS 7 machine as a build host. To setup vmware you'll probably want to run:

```
res/providers/provider.sh setup
res/providers/provider.sh limits
res/providers/provider.sh vmware
```

The first installs a few system tools/packages needed by `robox.sh` and other bundled scripts. The second increases the user resources limits so you don't run into problems. And finally the last one will grab/install VMWare Workstation (currently v15.5.0). 

Note you'll need to add a VMWare workstation serial number to the `.credentialsrc` file I previously mentioned (aka `export VMWARE_WORKSTATION=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX`) for the automatic VMWare install to work. Of course you can always look at the script and run the commands manually...
