### ISSUE TITLE
generic/centos7: Cannot sync folders with SMB and Hyper-V provider

### ISSUE THREAD

**Issue by AnthonyMastrean** [lavabit/robox#129]
I started with a generic/centos7 box.

```
vagrant init generic/centos10
```

And added a shared folder.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.synced_folder ".", "/vagrant"
end
```

When I try to bring it up, I get the following error. 

```
==> default: Mounting SMB shared folders...
    default: C:/Users/anthony/tmp => /vagrant
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o vers=2.0,credentials=/etc/smb_creds_vgt-7ccefee23710df0ff84b9be51a499a2b-6ad5fdbcbf2eaa93bd62f92333a2e6e5,uid=1000,gid=1000 //169.254.41.75/vgt-7ccefee23710df0ff84b9be51a499a2b-6ad5fdbcbf2eaa93bd62f92333a2e6e5 /vagrant

The error output from the last command was:

mount: wrong fs type, bad option, bad superblock on //169.254.41.75/vgt-7ccefee23710df0ff84b9be51a499a2b-6ad5fdbcbf2eaa93bd62f92333a2e6e5,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

I am on a work domain account, but I'm pretty sure I'm using the "correct" username format (per some obscure Vagrant issue/doc). I was able to share a folder with SMB and Hyper-V on a generic/debian10 box.

**Comment by timschumi** [comment]
This is probably more of a Vagrant issue (although it could indeed be fixed by just baking in the needed packages).

The way how those shared folder providers work is that the [guest-specific plugins](https://github.com/hashicorp/vagrant/tree/master/plugins/guests) tell Vagrant how to add support for a specific protocol (for example how to [install CIFS support on Debian](https://github.com/hashicorp/vagrant/blob/master/plugins/guests/debian/cap/smb.rb)).

A similiar piece of code is missing for CentOS/redhat: https://github.com/hashicorp/vagrant/tree/master/plugins/guests/redhat/cap

**Comment by AnthonyMastrean** [comment]
Oh, that's nasty. I'll open a Vagrant issue!
