### ISSUE TITLE
Add SLES boxes

### ISSUE THREAD

**Issue by stdevel** [lavabit/robox#133]
Hello folks,
first of all - thanks a lot for your effort on the generic boxes. They are helping me a lot for testing and development purposes.

My question is - do you have plans for also creating SLES boxes? I know that there are openSUSE boxes and beginning with SLES 15, openSUSE Leap 15 is a kind of upstream distro. But in some cases you will need a "real SLES" (*e.g. for testing some SUSE products*).

The process for crafting SLES boxes should be quite the same like for openSUSE Leap - you will just need to use a different ISO.

**Comment by abbbi** [comment]
hi,

if you are an SuSE customer with customer center access: SuSE provide its own SLES 12 vagrant images for both virtualbox and libvirtin the scc download center. There will also be an official SLES 15 vagrant image as with the release of SLES15SP2 in june 2020.

**Comment by stdevel** [comment]
Hey @abbbi, thanks for the hint. I knew about the upcoming update for SLE 15 SP2, but didn't know about the SLE 12 boxes. :)

**Comment by ladar** [comment]
@stdevel I don't have any SLES licenses and I don't personally suse OpenSUSE or SLES. 

I do use RHEL, so I was able to create unlicensed images using the RHEL installer DVD, but that required a bit of work, and it still isn't ideal, since the public images don't include updates.

I'd be willing to add SLES to the pipeline, if someone was willing to step up and create/maintain the config. But @abbbi is right, with official images available, there isn't much of a need, so it's up to you.

As an aside, the OpenSUSE config could also use improvement. It's currently stuck on 15.1 because 15.2 wasn't working (when I built the 2.0.6 images, haven't tried since). And it doesn't nearly as many tweaks/improvements as some of the other guests.

**Comment by abbbi** [comment]
for latest SLES builds (SP4) the boxes are not linked in the customer scc download center anymore, but are available via the openuse build service, in case anyone wonders:

https://build.opensuse.org/package/show/Virtualization:Appliances:Images:SLE-15-SP4/SLES-15-SP4-Vagrant

**Comment by stdevel** [comment]
That's interesting - thanks for sharing! I've already been wondering why the download links disappeared from SCC...

**Comment by ladar** [comment]
@abbbi @stdevel is there any reason we should add SLES to the Robox pipeline? Presumably we could use the same strategy as the RHEL boxes, which are released unregistered.

**Comment by stdevel** [comment]
This looks good, but where are the downloads? Can't find it on the website - checked all the tabs, etc.

**Comment by abbbi** [comment]
> This looks good, but where are the downloads? Can't find it on the website - checked all the tabs, etc.

on the right side, menu, images:

https://build.opensuse.org/package/binaries/Virtualization:Appliances:Images:SLE-15-SP5/SLES-15-SP5-Vagrant:libvirt/images
