### ISSUE TITLE
Can I get Hyper-V build metadata?

### ISSUE THREAD

**Issue by AnthonyMastrean** [lavabit/robox#134]
A coworker recently encountered the following error bringing up a generic box on the Hyper-V provider on Windows 10.

```
==> default: Importing a Hyper-V instance
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

Failed to import a virtual machine.

Error Code: 32784
Cause: VM version is unsupported
```

We compared Hyper-V Manager versions and determined that they were on the last cumulative update or something (10.0.17xxx). For example, I'm fully updated and my version is 10.0.18xxx.

![image](https://user-images.githubusercontent.com/217842/75362053-30741f80-5886-11ea-8436-5efce5df0254.png)

I wasn't even aware that Hyper-V could get cranky about VM versions. The only official docs on error code 32784 that I can find seem slightly related?

https://support.microsoft.com/en-us/help/2868279/importing-a-vm-that-is-exported-from-windows-server-2012-r2-into-windo

Anyway, they're working on getting Windows updates going (they were "stuck", as it happens). But, I was wondering if there's any Hyper-V build or version metadata in the final box output or somewhere in your build logs or something if this happens again and I want to pinpoint the problem?

**Comment by timschumi** [comment]
Once you downloaded/imported a box, you will be able to find all of its components in your vagrant.d directory (for me it's `~/.vagrant.d/boxes` on Linux). I don't know where it is on Windows though.

**Comment by ladar** [comment]
@AnthonyMastrean I'm not quite sure what metadata you're asking for ... the `packer` config is available in the `generic-hyperv.json` file. You'll note `packer` is creating [generation 1](https://www.packer.io/docs/builders/hyperv-iso.html#generation) virtual machines, since that seemed to have the broadest compatibility with hosts/guests.

As for the build host ... it's Windows 10 machine ... that gets updated periodically. It's currently building the 3.0.0 boxes. The host update status _shouldn't_ matter, but if I'm wrong, let me know and I'll make sure to update it before the next release.

**Comment by AnthonyMastrean** [comment]
@ladar I'm not *certain* yet! I've only seen this issue once and it went away after my coworker updated their machine 🤷
