### ISSUE TITLE
Difference between ubuntu generic 20 3.0.14 and 3.0.16

### ISSUE THREAD

**Issue by matthew-gill** [lavabit/robox#165]
Hey... think title says it all, just wondering what the difference is please!

**Comment by ladar** [comment]
I accidentally ran `rm -rf` while waiting for the `3.0.16` boxes to finish uploading. So rather than wait until i could rebuild, I simply used the `3.0.14` images for the boxes that got wiped out... 

I was already building `3.0.18`, which is now uploading (and has been for the last 8 hours). Si that should be out soon.

The `3.0.18` release includes completely rebuilt images for every box, with the exception of those built Parallels (the Mac is offline), and DragonflyBSD 5 on Hyper-V, which I haven't been able to rebuild in quite awhile.

When I can't build something, generally I carry forward the existing image, so it doesn't hold up the overall release. 

Why do I release everything? So when users get presented with a platform choice, they see all the options. Not just those available in the most recent version.

I just brought new build bots online so I'm working out the kinks, hence the rapid rebuilds. I'll probably kick off another rebuild soon, with the bigger disk sizes.
