### ISSUE TITLE
debian10 x32 variant

### ISSUE THREAD

**Issue by ladar** [lavabit/robox#199]
@timschumi any interest in adding Debian 10 as another x32 variation? It seems like to a good time to add more. Personally, I would like to see x32 variants for FreeBSD, CentOS 7 and Alpine 3.13, but that's just me. Those distros strike me as likely to still have a respectable number of x32 bit users, but that's just a guess.

**Comment by timschumi** [comment]
While I don't have any use for those variations personally (which means that I don't have a reasonably well tested configuration on hand right now), I won't mind looking into it. The reason why I focused on Debian so far was because of the (in my opinion) worse than average multiarch support and because most applications (including mine) target Debian or something Debian-based as their baseline for compatibility.
