### ISSUE TITLE
Ideas for speeding up builds

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#20]
robox is a wonderfully comprehensive collection of base boxes covering a wide variety of different operating systems. I gather that time to pack all these boxes is a constraint on further development, so I wonder if we can improve packing time somehow.

For example, is there a significant restriction on build resources, RAM, CPU cores, and so on? Perhaps we could provide a donation link specifically for funding cloud resources used to build our images.

That could help with the hardware constraints on build time, by scaling vertically. Could we also scale horizontally? Perhaps building boxes from a pool of hosts.

Finally, what steps can we take to improve the build time of each particular box? I've done some (premature) optimizations on my own box templates, such as minifying `boot_command` contents, and compressing provisioning media, as keyboard input delivery and FTP can be run slowly on certain virtual guests.

Honestly, the bottlenecks of OS installation tend to be the long, uncontrolled process of running the install wizards. But what other things can we shave off, even just a few minutes from each build? Reducing boot splash timeouts, selecting faster virtual hardware (when guest compatible), and ensuring that installation media (ISO's, IMG's) are sourced from fast online caches. Any other ideas for accelerating builds?

**Comment by ladar** [comment]
> For example, is there a significant restriction on build resources, RAM, CPU cores, and so on? Perhaps we could provide a donation link specifically for funding cloud resources used to build our images.

I've been meaning to setup a donation link, but haven't had a chance yet. Will soon.

> That could help with the hardware constraints on build time, by scaling vertically. Could we also scale horizontally? Perhaps building boxes from a pool of hosts.

I already am scaling horizontally. I usually task anywhere from 4 to 8 machines with building the images (depending on what I spare). My biggest bottleneck is the Win and Mac robots. I only have 1 of each, any they are both 7+ year old notebooks. They both take 48 to 96 hours to complete a full build at this point. The Gentoo images alone take 2+ hours. On Linux side, I'm slightly better equipped, in that I have a few machines to split across, but builds still take 24-36 hours. 

Ideally I'd like to get 1U servers for each platform (Win, Mac, Linux) that are optimized for virtualization, with lots of ram, cores, and ssd arrays. The servers I currently use all have old fashioned magnetic disks, and the notebooks I use lack the cores/ram, so thy are all limited to building 1 or 2 images at a time. 

Unfortunately I can't justify spending 5k to 10k on dedicated hardware for what is essentially a side project. I recently started putting out feelers to see if I could find someone to sponsor the hardware...

I tried renting machines via packet.net. Their hourly rates were reasonable enough and their hardware could build all of the images for a provider in 1 or 2 hours. Unfortunately the cost of bandwidth of was prohibitive. A full build generates roughly 1 TERAbyte of network traffic. The resulting images alone are 300+ GIGAbytes. 

If I am able to get better hardware, I'd plan to start generating docker, and OVA variants (with the latter available on roboxes.org). And of course add more distros.

> Finally, what steps can we take to improve the build time of each particular box? I've done some (premature) optimizations on my own box templates, such as minifying boot_command contents, and compressing provisioning media, as keyboard input delivery and FTP can be run slowly on certain virtual guests.

I've spent a ton of time optimizing my current process. I created the `robox.sh validate`, `robox.sh links` and `robox.sh cache` commands so I can validate templates, and verify links are still good, and precache the install ISOs. That saves a lot of time (a few of the ISOs are on slow servers, and take awhile to download), and ensures that when I kick off my single file builds, the bots are working, and don't break randomly.

> Honestly, the bottlenecks of OS installation tend to be the long, uncontrolled process of running the install wizards. But what other things can we shave off, even just a few minutes from each build? Reducing boot splash timeouts, selecting faster virtual hardware (when guest compatible), and ensuring that installation media (ISO's, IMG's) are sourced from fast online caches. Any other ideas for accelerating builds?

Network access hasn't been a problem. I'm spitting builds across 3 gigabit links. My bottlenecks are CPUs and IO (aka disk speed). I've already optimized the biggest bottlenecks (downloading the ISOs and uploading images).

There are couple of spots I could shave a minute or two, at the expense of reliable automation... but shaving a minute or two off a 3 day process seems pointless. If I'm going to speed things up any more, it will probably have to come from access to better hardware.

**Comment by ladar** [comment]
> For example, is there a significant restriction on build resources, RAM, CPU cores, and so on? Perhaps we could provide a donation link specifically for funding cloud resources used to build our images.

I've been meaning to setup a donation link, but haven't had a chance yet. Will soon.

> That could help with the hardware constraints on build time, by scaling vertically. Could we also scale horizontally? Perhaps building boxes from a pool of hosts.

I already am scaling horizontally. I usually task anywhere from 4 to 8 machines with building the boxes (depending on what I can spare). My biggest bottleneck is the Win and Mac build bots. I only have 1 of each, and they are both 7+ year old notebooks. The HyperV and Parallels boxes already take 48 to 96 hours to finish. The HyperV/Parallels Gentoo boxes 2+ hours. Unless I get better/more hardware, I will probably have to selectively drop support for HyperV and Parallels in the future. On Linux side, I'm slightly better equipped, as I have several bots.

Ideally I'd like to get 1U servers for each platform (Win, Mac, Linux) that are optimized for virtualization, with lots of ram, cores, and ssd arrays. The servers I currently use all have old fashioned magnetic disks, so the end up bottle necking on disk IO, while the notebooks I task, all get bottlenecked by their limited number of cores/ram. Basically I'm limited to building 1 or 2 images at a time. Any more and things start breaking (boot command timing, getting updates, etc).

Unfortunately I can't justify spending 5k-10k for dedicated hardware. I'm trying to find find a sponsor, but haven't yet.

I've also tried renting machines on packet.net. Their hourly rates were reasonable enough. With their servers, I was able build 10 - 20 images in parallel, so each provider only took 1 or 2 hours to finish, which is only $1 or $2. But the cost of bandwidth didn't work. A full build generates roughly 1 TERAbyte of network traffic, which means each build probably cost $100 to $200 at this point.

> Finally, what steps can we take to improve the build time of each particular box? I've done some (premature) optimizations on my own box templates, such as minifying boot_command contents, and compressing provisioning media, as keyboard input delivery and FTP can be run slowly on certain virtual guests.

I've spent a ton of time optimizing my current process. I created the `robox.sh validate` and `robox.sh links` commands so I can validate templates, and verify links are still good before a build begins. And I created the `robox.sh cache` command so I can download ISOs ahead of time. I recently removed the upload step from my packer configs as well. It seems that when I have 2+ robots building and uploading, I start running into problems with the Vagrant cloud, which was causing the process to stall, as packer re-tried the upload. 

> Honestly, the bottlenecks of OS installation tend to be the long, uncontrolled process of running the install wizards. But what other things can we shave off, even just a few minutes from each build? Reducing boot splash timeouts, selecting faster virtual hardware (when guest compatible), and ensuring that installation media (ISO's, IMG's) are sourced from fast online caches. Any other ideas for accelerating builds?

With 3 gigabit links, network access isn't much of bottleneck. It's the number of CPUs and disk IO with the hardware I have that limits my robots to building 1 or 2 images at a time. 

There are certainly places where you can shave time, but shaving a minute or two off a 3 day process seems pointless, especially if it causes a build to break. If that happens packer ends up stalling for 1-2 hours before it times out and continues on.

Hence, I'm somewhat limited, until I get better hardware. If I do get better hardware (either fast notebooks, or 1U servers), I plan to add more distros. But I also want start generating docker, and OVA variants which people could download off roboxes.org. Right now I'm only building a few docker images, and one OVA. I'd also like to build the images weekly, instead of every 2-4 weeks.

**Comment by mcandre** [comment]
Wow, we're stretching our resources to the limit!

Curious if the Gentoo build could at least be sped up. I'm not sure if you're using a hardcore stage 3 install method? Perhaps the "Minimal Install CD" could provide a faster nothing-to-SSH packer build

**Comment by ladar** [comment]
@mcandre ...

> Curious if the Gentoo build could at least be sped up. I'm not sure if you're using a hardcore stage 3 install method? Perhaps the "Minimal Install CD" could provide a faster nothing-to-SSH packer build.

I believe the Gentoo image is in fact using a stage 3 install disc, but I don't consider myself enough of a Gentoo expert to overhaul that build config. And while the Gentoo box itself takes 2x to 6x longer than average, the two Gentoo images for each provider, are combined, still less than 10% of the overall time. 

I was able to get my hands on a blade chassis, with four blades, each with dual 6-core Xeons, but they need memory, and SSDs before I can start using them. (And I might need a Windows Server license as well.) I'm hoping to get those parts donated, but it hasn't happened yet. 

I did add the donation links you suggested to the Github readme/website, but so far no takers.
