### ISSUE TITLE
Parallels box generic/ubuntu2110 v3.6.6 can not be downloaded

### ISSUE THREAD

**Issue by borisceranic** [lavabit/robox#232]
When trying to update generic/ubuntu2110 box from version v3.6.4 to v3.6.6, vagrant fails with a following error:

```
$ vagrant box update
==> dockerbox: Checking for updates to 'generic/ubuntu2110'
    dockerbox: Latest installed version: 3.6.4
    dockerbox: Version constraints:
    dockerbox: Provider: parallels
==> dockerbox: Updating 'generic/ubuntu2110' with provider 'parallels' from version
==> dockerbox: '3.6.4' to '3.6.6'...
==> dockerbox: Loading metadata for box 'https://vagrantcloud.com/generic/ubuntu2110'
==> dockerbox: Adding box 'generic/ubuntu2110' (v3.6.6) for provider: parallels
    dockerbox: Downloading: https://vagrantcloud.com/generic/boxes/ubuntu2110/versions/3.6.6/providers/parallels.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404
```

Upon further inspection, the version page for the said box contains a table with a list of providers for which boxes are released, and parallels provider box is 0 bytes in size. Screenshot of page https://app.vagrantup.com/generic/boxes/ubuntu2110/versions/3.6.6 embedded for your convenience:

<img width="763" alt="Screenshot 2022-01-31 at 16 36 51" src="https://user-images.githubusercontent.com/53285/151823461-d623eada-a598-4279-b81f-45261596bc0e.png">

Can someone please look into this?

**Comment by ladar** [comment]
@borisceranic there was an error during upload. I've uploaded the box again, so it should be working now. If this happens again, you can workaround it by manually specifying a previous version until the issue is caught and the box uploaded properly. Unfortunately, because of the way the scripts work right now, they can't detect this particular issue when the box is uploaded.

I've let HashiCorp and @chrisroberts know about the issue here https://github.com/hashicorp/vagrant_cloud/issues/74

And hopefully @VincentSaelzler is working on a system that will catch this type of issue automatically.
