### ISSUE TITLE
Request Pop!_OS box

### ISSUE THREAD

**Issue by BartKeulen** [lavabit/robox#246]
I have been using your Ubuntu boxes for a while now and I really like them. I was wondering if you could create a [Pop!_OS](https://pop.system76.com/) box?

**Comment by ladar** [comment]
@BartKeulen hi Bart, I've only read about Pop - never used it myself - but as I understand it, its distinctions are support for System 76 hardware (just like PureOS is made for Librem hardware) and a customized GUI. As such, would there be much value in a virtualized. console/command line box? Or would it be identical in terms of CLI, ABI, etc, to Ubuntu?

In a perfect world, I'd add it to the pipeline anyways, even with only minor differences. I'd also like to create GUI variants of the existing configs, which boot to a graphical desktop, and have the standard GUI apps pre-installed. Unfortunately, the blade servers I have for this project just hit 12 years old (Dell C6100 with Dual Xeon 5500s), so I'm a little limited by the hardware available. It currently takes almost 50 hours to build the eisting configs, and since GUI installs would require more packages, it's logical to assume they'd take even longer if we added them.

I wrote the above blurb on the off chance you have a contact with System 76, and they might be willing to donate modern replacement servers? We have additional units/bandwidth in our rack, but we're close to the limit on our power circuit, so we'd need to replace the existing systems with newer. more power efficient systems if we want to add capacity.

**Comment by BartKeulen** [comment]
Pop is meant to be a general distro and not one specifically for System 76 hardware as far as I know. It has some differences to Ubuntu (https://support.system76.com/articles/difference-between-pop-ubuntu) on which it is based. But I don't think Pop ships without a GUI. Reading your reply I understand that now is not the right time to add Pop to your collection of boxes, maybe in the future. Unfortunately I cannot help you with servers, I am in no way affiliated or in contact with System 76.
