### ISSUE TITLE
instructions for how to build hyperv box?

### ISSUE THREAD

**Issue by TonyApuzzo** [lavabit/robox#249]
Hi,

Please, I need instructions for box building with hyperv. I haven't been able to figure out how to build hyperv boxes.

I played around with a few different options, noticed that the robox.sh script is WSL aware, so I installed Oracle Linux 7.9 to be the closest thing to RHEL available for WSL on the Microsoft Store and then

```bash
sudo yum -y install git
sudo ./res/providers/providers.sh setup
sudo ./res/providers/providers.sh packer
 ./robox.sh box generic-opensuse-hyperv
```

But it just takes a second and then exits with 0

I tried `sudo ./res/providers/providers.sh hyperv` but that gives an error since hyperv seems to be special.

What am I missing?

Thank you!

**Comment by JGillam** [comment]
I'm not an expert on this but I have been running Vagrant boxes with hyperv providers so maybe this will help. I usually run `vagrant up` from a powershell console when doing this with no problems.  Unfortunately it must be running as admin to interact with Hyperv.  I'm not sure how running it from within WSL (if even possible) provides any advantages since HyperV will be outside of WSL anyway.

**Comment by ladar** [comment]
Hi @TonyApuzzo .... @peyton005 is supposed to be working on an update to the README file, so it includes some of the info you need.

The easiest way to build a box from scratch is launch a DOS shell, and assuming the packer.exe is in your search path, Hyper-V is installed correctly, and the permissions are setup, you can run the following:

```dos
SET VERSION=1.0.0
packer build -only=generic-opensuse15-hyperv generic-hyperv.json
```
If you get a permissions error, you can try launching the DOS shell with admin privileges.

With regards to WSL, it is required to use the various bash management scripts in the project repo. Like `./robox.sh links` or `./robox.sh cleanup` for example. It's also required to use various other scripts, like the box uploaders in `res/scripts`  ... that said, I don't believe you can use `./robox.sh box generic-opensuse15-hyperv` to build the box. That's because you need to install the Windows version of Packer on your host, and, at least when I gave it a cursory attempt, I couldn't run that executable from within the WSL environment.

I will also offer congrats on using the `providers.sh` script correctly, but alas, it only knows how to setup the Linux hypervisors (docker/vmware/virtualbox/libvirt), and does NOT have any logic for Hyper-V or Parallels.

i would welcome a BAT or PS providers script, which automates the setup on Windows. 

Finally, you said there was an issue with the OpenSUSE `sshd` config. Can you elaborate?

**Comment by Hilljackcantspell** [comment]
> Hi,
> 
> Please, I need instructions for box building with hyperv. I haven't been able to figure out how to build hyperv boxes.
> 
> I played around with a few different options, noticed that the robox.sh script is WSL aware, so I installed Oracle Linux 7.9 to be the closest thing to RHEL available for WSL on the Microsoft Store and then
> 
> ```shell
> sudo yum -y install git
> sudo ./res/providers/providers.sh setup
> sudo ./res/providers/providers.sh packer
>  ./robox.sh box generic-opensuse-hyperv
> ```
> 
> But it just takes a second and then exits with 0
> 
> I tried `sudo ./res/providers/providers.sh hyperv` but that gives an error since hyperv seems to be special.
> 
> What am I missing?
> 
> Thank you!

**Comment by Hilljackcantspell** [comment]
static  let  three :   [Float]  =  [0,  1,  1,  1,  1,  0,  //

**Comment by Hilljackcantspell** [comment]
Training a Neural Network to Recognize Digits

**Comment by TonyApuzzo** [comment]
The HyperV box for OpenSuse is working again, thank you!
