### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jacksonporter** [lavabit/robox#253]
Hi! Thanks so much for your contribution!

I was wondering if you can add a `LICENSE` to this project? This allows for open-source use of your code (right now nothing is set, so the lines are gray). 

Suggested `LICENSE` - based on MIT

Thanks!

**Comment by ladar** [comment]
I've thought about this in the past, and it's a rather complicated issue if you really understand things. That's because this repo is actually working with and utilizing so many hypervisor platforms, operating system distros, and other support tools on both the build robots, and inside the guest images, and all of those use different licenses, running the gamut from OSI approved, to commercial. And I felt it would be improper to publish a license file, like you suggest which might lead people to think everything this repo touches will also carries the MIT license. 

I think wrote a short blurb to this effectr years ago, and stated that all the scripts and configs I've created, and stored int his repo are placed in the public domain.

**Comment by jacksonporter** [comment]
Indeed it is complex and completely understand your point as well. Thanks for the additional context!

**Comment by ladar** [comment]
Oh I almost forgot. What license applies to the box images files themselves!

**Comment by ladar** [comment]
See #19.

**Comment by ladar** [comment]
If you feel obliged, it might worth adding a little disclaimer to effect of what I said above to the bottom of the README file.

**Comment by ladar** [comment]
I haven't done it, because it would need to have all the usual disclaimers and such.
