### ISSUE TITLE
Shrink boxes

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#26]
We can strip out some components to reduce total image size, see the cleanup scripts in https://github.com/mcandre/packer-templates for examples. In general, caches should be cleaned, including /tmp mounts and any OS package manager caches.

We can shrink images even further by removing some nonessential software packages, like perl in Ubuntu, that aren't strictly needed in order to boot up and serve SSH commands. This could break some user expectations, of course, so it's up to you to decide how minimal or maximal we want the base boxes to be.

**Comment by ladar** [comment]
@mcandre I agree, some of the distros could be made smaller. I have the most experience with CentOS/RHEL so those distros are relatively well tuned, and clean. With the other distros, I did less cleaning, but I'd rather have slightly larger image files that "just work" ... so I was cautious in what I remove. If your an expert, and know for certain removing a temp/cache file, etc, won't break anything, please submit a pull request ... each distro has it's own cleanup script.

Also, keep in mind that I wanted these CLI environments to be capable of a little more than booting+SSH out of the box. My goal is to drop users into a bash shell, and have it setup with the most basic utils/commands pre-installed. The list is a little inconsistent, since I only add a package when I discover a rudimentry command is missing, ie. `ps` , `ifconfig` , `nslookup` , `locate`, `grep` , etc, and I don't use all of the images equally. So if you find a major deficiency, suggest an inclusion. 

I figure if someone wants a stripped down, bare bones image, they'll either build it from scratch, because they know precisely the software to install (I use this strategy myself for my private appliance images), or they'll use an official distro image. 

Personally I found many of the official images were small, but broken in seemingly random, and frustrating ways. As a result, basic compile/install commands, which would work on a manually installed minimal version of the same distro, would fail inside the official VM. 

Eventually I decided to release my own images, starting with the distros I used frequently, and add new ones, as I need them. My goal is to keep the configs close the default/simple... as in, I want the roboxes to be similar to what you'd have if you installed the same distro manually. As a result, if `perl` is part of the default minimal package set for Ubuntu, it stays. 

I've started building more container images, `docker` in particular, and that is a trickier problem, as a lot more can be removed. Unfortunately, I've had a hard time finding a good guide as to what the best practices are when it comes to removing various files... which is why I only push CentOS 6/7 images at the moment. And even with the CentOS images, I ended up having to comment out many of my original exclusions because the skinny image couldn't run the malware/virus scanners I was trying to use.

**Comment by ladar** [comment]
@mcandre I'm gonna close this issue. If you have specific commands that you think should be run during the cleanup stage, please submit them as a pull request against the relevant distro cleanup script in my repo.

I agree that package manager caches should be cleaned, installer logs removed, system log files truncated, and temp files removed. And I do that with some of the cleanup scripts. But I haven't had time to audit all 32 distros to make sure all of those steps are being done properly. 

I tried using a generic `find /var/log/` command to delete log files in the past, but found that with some distros, not having the log file exist already, with the correct permissions, caused problems.

I'm also certain more could be done to cleanup the BSD configs. And the Gentoo/Arch/SUSE builds, as I'm less familiar with  those package managers, and was afraid of breaking things.  Since I only have the resources for limited testing of the boxes after each build, I err on the side caution.

**Comment by mcandre** [comment]
> I tried using a generic find /var/log/ command to delete log files in the past, but found that with some distros, not having the log file exist already, with the correct permissions, caused problems.

Correct. I learned the hard way that for `/var/log` entries it is better to truncate the file contents than to delete the files. See the cleanup script examples in the template link at the top of the original post for this issue.
