### ISSUE TITLE
Feature request: Ubuntu vagrant boxes with ubuntu-desktop-minimal

### ISSUE THREAD

**Issue by GeFrIt42** [lavabit/robox#263]
Hello,

I have the need to have a Desktop Environment in my Ubuntu boxes, at the moment I am provisioning it  but this take quite a lot of time.

Would be possible to generate the Ubuntu boxes with ubuntu-desktop-minimal ?
maybe called _**generic/ubuntu1804-desktop-minimal**_ ?

**Comment by ladar** [comment]
@GeFrIt42 yes, we'd like to, but we don't have hardware/capacity to add desktop versions right now. If/when were able to replace our blade servers (currently using Dell C6100s) with something newer/faster, we can add these.

**Comment by abbbi** [comment]
@ladar have you considered asking https://osuosl.org/ for hardware? They sponsor quite lots of other projects (https://osuosl.org/communities/), helping them with co-locations for build intensive tasks (such as the debian reproducible build project, for example)

**Comment by ladar** [comment]
@abbbi no I haven't. The Lavabit data center has plenty of available rack units, and our uplink is plenty fast (20 gigabits). The constraints is power.  We currently use 6 blades for the robox build pipeline, and they're ancient. The other blades in the chassis consume the images for our CI system.

I've tried applying for grants in the past, but alas its usually an involved, time consuming process, with a low success rate. and I'm pretty short on time. And I already devote far more time to this project than I should, sadly. 

All that being said, if you know the folks at OSU, then perhaps you can reach out to them on my behalf and get the ball rolling?

**Comment by ladar** [comment]
@abbbi i forgot to mention, I've had people offer cloud computing time in the past that isn't a good fit for this project for a bunch of reasons. Starting with resources. We use between ~3 and ~4 TiB of data transfer with each run. Because we beuild each image using the hypervisor its meant for, we need to be running on metal. 

I also prefer to control the hardware from a security standpoint. Although I don't mind leveraring the cloud for extraneous tasks that aren't security sensitive. For example, I looked into using Travis to setup a test framework that would make sure new boxes work as expected. But I couldn't get it work on their old dot org platform, which didn't have resource limits. And even though they gave us f/oss credits for the new dot com system, it felt like we'd burn through the credits to fast to justify the dev time to make it all work.

**Comment by GeFrIt42** [comment]
@ladar  : thanks for all the clarifications, I think there is no point to keep this issue open, I'll close it.
