### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Enmk** [lavabit/robox#264]
Can't find license information anywhere on this repo, could you please make it explicit?
Is it MIT? Is it GPL? Or is it Apache 2.0 ?

**Comment by ladar** [comment]
See #253 ... as far as I'm concerned the scripts used by this repo can be considered part of the public domain. However the software/tools and other resources they rely upon are all governed by their own license.

**Comment by Enmk** [comment]
I get that there are many tools involved in building boxes, but what is the license of the code in this repo itself? All the `.json` and script-files

If you consider that to be a public domain, why not just mark it as such in a License file or why not just use MIT license as the simplest and shortest one (easiest to understand) ?

**Comment by ladar** [comment]
@Enmk because including a LICENSE file in the repo might mislead some people to think the license might apply to boxes that are generated, or tools which are being used.

As I've said, I consider the scripts/configs I've created for the Robox project to be in the public domain. And ideally, I would write/add a section ot the README which states this, along with a notice/explanation which lets me people know the tools/boxes, etc, use other licenses. But it's a low priority, and I have't had the time.

@Enmk if you're a good writer, we really good use help adding info to the README and/or wiki. Not just about the license issue, but also about how ot use the scripts in the repo to build boxes, how to add new box configs, and get them added to the release pipeline, and how to actually consume the boxes themselves.
