### ISSUE TITLE
Fedora boxes do not support vboxsf

### ISSUE THREAD

**Issue by najamelan** [lavabit/robox#27]
I'm trying to use roboxes/fedora29 but I'm running into issues when trying to have a synced folder.

Apparently the fedora package virtualbox-guest-additions.x86_64 does not supply the vboxsf file system. See this [redhat bug](https://bugzilla.redhat.com/show_bug.cgi?id=1576585#c1) and [this one](https://bugzilla.redhat.com/show_bug.cgi?id=1576832) for discussion. 

Currently the vbguest plugin also fails to properly install the guest additions with [this bug](https://github.com/dotless-de/vagrant-vbguest/issues/278).

So I'm wondering if there is a way of getting a fedora in a virtual machine with synced folders and being able to do `vagrant destroy` and `vagrant up` and have it working without having to roll one's own fedora box. 

Maybe using nfs is a solution, but my networking setup is a bit complex, so I haven't gotten round to that.

I don't know if roboxes could create a box compatible with synced folders, but I thought I should at least report the current state of affairs.

**Comment by ladar** [comment]
@najamelan I don't personally use, or test folder syncing, so it doesn't surprise me that this feature is broken on one or more of the boxes. As a short term fix, have you tried using the `vagrant upload` command? It uses SSH/SCP to push files into a box, and has worked well for me. 

As for fixing this issue, it sounds like adding the [akmod-VirtualBox](https://download1.rpmfusion.org/free/fedora/releases/29/Everything/x86_64/os/Packages/a/akmod-VirtualBox-5.2.20-1.fc29.x86_64.rpm) RPM will fix it. Alternatively switching back to building the Vbox components from source is an option. 

I'm hesitant to ship RPMfusion repo with the roboxes, because it isn't what the user would 'expect' but adding this single RPM shouldn't be a problem, provided it fixes sync'ed folders, and doesn't cause problems when the kernel is updated.

Do you have a suggestion for how we can modify the applicable config script to fix this?

https://github.com/lavabit/robox/blob/master/scripts/fedora29/virtualbox.sh
