### ISSUE TITLE
Alpine 3.18 vagrant hyper-v box request.

### ISSUE THREAD

**Issue by elico** [lavabit/robox#273]
In the pending list there is not Alpine linux 3.18 which is new.
Can you please add it?

**Comment by dmitry-j-mikhin** [comment]
Alpine 3.18 support has been added in https://github.com/lavabit/robox/commit/c389d8c06463666e90a87cda8fad01517089e079. But there are no active versions yet at https://app.vagrantup.com/generic/boxes/alpine318:
![изображение](https://github.com/lavabit/robox/assets/41896087/cc640d5d-ee43-431f-b2b3-94ada4b4a615)

**Comment by elico** [comment]
@dmitry-j-mikhin +1

**Comment by ladar** [comment]
I added the config, so it will get uploaded with the 4.3.0. 

Since I took time off from this project, this release is requiring more work than normal, as it includes several new configs, lots of existing config upgrades, plus several older box configs which are broken, end of life, etc, so I can't predict when it will get uploaded.

**Comment by dmitry-j-mikhin** [comment]
@ladar thanks for the explanation, we'll wait.
