### ISSUE TITLE
Haiku Beta 1

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#28]
Now that Haiku has released a more stable beta, could we get a base box for Haiku?

https://www.haiku-os.org/get-haiku/

Here's an example packer template for Haiku alpha:

https://github.com/mcandre/packer-templates/tree/master/haiku

**Comment by ladar** [comment]
Unfortunately adding your templates to the larger `robox` workflow would take a little bit of work. It's also unclear if the scancode, aka `fix-6001`, patch is part of the upstream `packer` repo. Otherwise it would need to be added to the growing patch stack in `res/providers/`.

Your repo is designed to keep all the boxes separate, since you build them 1 at a time, and only on occasionally. My repo groups boxes by provider type, to make it easy to build, and rebuild, all of the box configurations periodically. Merging the two takes work, and I'm short on time right now. 

Mind if I ask why this particular OS? And, any particular reason the box below won't do what you need?  

https://app.vagrantup.com/haiku-os/boxes/r1beta1-x86_64

**Comment by mcandre** [comment]
Haiku represents an interesting UNIX implementation to me. It carries principles of BeOS forward into modern computing systems. This is timely; They just released Beta 3.

https://lunduke.substack.com/p/haiku-the-alternative-os-grows-up

**Comment by mcandre** [comment]
Regarding patches, if I remember correctly, this work has spurred HashiCorp to refactor their entire scancode system to enable more keyboard keys to be used for Packer builds.
