### ISSUE TITLE
SmartOS base box

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#29]
Example packer template:

https://github.com/mcandre/packer-templates/tree/master/smartos

**Comment by ladar** [comment]
Unfortunately adding your templates to the larger `robox` workflow would take a little bit of work. It's also unclear if the live distribution patch was part of the upstream `packer` repo. Otherwise it would need to be added to the growing patch stack in `res/providers/`.

Like I said regarding `Haiku`, your repo is designed to keep all the boxes separate, since you build them 1 at a time, and only on occasion. My repo groups boxes by provider type, to make it easy to build, and rebuild, all of the box configurations periodically. Merging the two takes work, and I'm short on time right now.

Mind if I ask why this particular OS? I don't think I even know enough about it to know if I'm building it right. Based on a cursory review, it appears to be similar to Qubes...

https://app.vagrantup.com/haiku-os/boxes/r1beta1-x86_64
