### ISSUE TITLE
9p and NFS support for Vagrant

### ISSUE THREAD

**Issue by timschumi** [lavabit/robox#52]
Would it be possible to add 9p and NFS support into Vagrant libvirt boxes by default, since VirtualBox shares aren't available there and those are (afaik) the only other options for mounts that don't have to be synced manually?

**Comment by ladar** [comment]
Feel free to submit a pull request. For the libvirt boxes, add the necessary changes to the qemu.sh script...

**Comment by furlongm** [comment]
As an alternative to this, the vagrant-sshfs plugin supports most platforms and might be a a more generic option to install? It just requires the guest has the sshfs client installed.

**Comment by timschumi** [comment]
@furlongm sshfs indeed seems like a good alternative for the time being, so I submitted a PR to vagrant-sshfs to add alpine support. Thanks for the suggestion!

@ladar I didn't notice that vagrant doesn't support alpine boxes by default, but the vagrant-alpine plugin seems to successfully add NFS and 9p installation support. I'll close the issue since that works equally well as if the support would have been added to the box by default (except of course that the box would be more bloated for the people who don't need it).

**Comment by ladar** [comment]
@timschumi adding NFS support (and possibly 9p) isn't unreasonable, provided it doesn't add much to the image size, and doesn't expose the images to any potential security problems/issues.

I just needed to know how to do it, since it isn't a `vagrant` feature I normally use, and don't really have the means to test. 

If the Alpine plugin makes the changes, perhaps you can convert what its doing into a series of shell commands? If so, just post them here, or open a pull request. And be sure to let me know the if we should be running these commands only on Alpine (presumably from 3.5 forward), or other distros. Also, whether the config steps are only needed by the VirtualBox provider, or do all the `vagrant` providers make use of NFS for shared folders?

P.S. In re-reading this issue it appears I mentioned `qemu.sh` for any `libvirt` specific configuration steps, when in fact you were discussing VirtualBox. My apologies. 

P.P.S. I'm hoping `vagrant` will someday (soon) include Alpine support by default. https://github.com/hashicorp/vagrant/issues/10584

**Comment by timschumi** [comment]
Plugins for guest OSes work that way, that they somehow recognize the OS running (in the case of the libvirt alpine boxes that check is hardcoded to the `alt` type, as already discussed in the issue you linked, which broke the vagrant-alpine plugin and therefore NFS) and they define certain capabilities (for NFS it would be nfs_client_install and nfs_client_installed) that do certain actions within the box.

The appropriate code from the vagrant-alpine plugin can be found [here](https://github.com/maier/vagrant-alpine/blob/master/lib/vagrant-alpine/cap/nfs_client.rb). A lot of this could probably be cleaned up though since it handles issues with outdated custom builds of the boxes, which is probably why it wasn't upstreamed yet.

Again, I think having that as a plugin (until it's upstreamed into vagrant) is the better solution, since you don't have to install additional packages and services onto the boxes. I'll try and cleanup the alpine plugin a bit and open a pull-request against upstream vagrant to see what they think of it.

Re: PS: I was talking about libvirt, I just mentioned that it has nothing comparable to VirtualBox shares out-of-the-box. Again, I wasn't aware of the Alpine plugin back then.

**Comment by ladar** [comment]
I'm all for tweaking the roboxes so they "just work" by default. So if all shared folder support requires is the NFS client utils, and it only requires those 3 commands, I don't have an issue with it.

I just need to know that making this change will a) fix the issue, and b) not break any of the 30 Alpine boxes (6 versions 3.5 to 3.10, across 5 hypervisors) and c) the RPC service socket isn't exposed to the network by default. I don't supposed you can test it out? 

My current CI server is virtualized, which makes automating periodic testing tough. The process now involves kicking off scripts on my notebook, and then ignoring my computer for a weekend. But that was with gigabit. At the moment I'm overseas, with only an 8 megabit uplink. 

```
apk add --upgrade nfs-utils
rc-update add rpc.statd
rc-service rpc.statd start
```

If you'd prefer to spend the time cleaning up the Alpine plugin so it can be accepted upstream, that works too!

**Comment by timschumi** [comment]
I can and probably will test those commands to see if they have any of the issues that you mentioned.

The problem right now is that it won't work out of the box no matter what, since the boxtype `alt` confuses that system massively. Even if the NFS utils are installed by default, it wouldn't be able to detect them (since it tries to query the package state through `yum`). After that, it would try to install the NFS utils, which again fails due to `yum`.

Those are the reasons why I want to make the vagrant-alpine plugin ready for upstreaming, since it would remove the requirement for hardcoding the box type AND resolve the NFS issues all within the same fix (in addition to not having to touch the boxes themselves).

**Comment by ladar** [comment]
If your going to test the above commands, you could also try overriding bundled Vagrantfile guest type, aka `:alt` with the value `:linux` ... to see what happens. As I recall `vagrant up && vagrant ssh` failed without it, so you'll know pretty quickly if the bug still exists.

The `:alt` fix was needed 2+ years ago. It's possible, perhaps even likely that `vagrant`, or the `vagrant-libvirt` plugin have fixed whatever the issue was. I made that change before the `robox` repo was public and a lot of the commits got lost during the transition (I had to sanitize certain files from the history before I could upload it to GitHub).

It's also possible the issue was with Alpine and their newer kernels, etc, have fixed the issue. I'm just weary to make a change this significant without testing it thoroughly first, across all the different variants, since it might fatally break the provisioning process.

**Comment by ladar** [comment]
I tracked down the commit where I added `:alt` and it was Nov 2017. I didn't log details on the problem, but I did note that the automatic guest detection caused the box to fail provisioning. Forcing the the `:alt` guest type avoided the provisioning steps that were failing fatally. 

If your really curious track down one of the Alpine 3.5 images from Oct 2017, and see what happens. Of course a true test would require using the Oct 2017 version of `vagrant` and `vagrant-libvirt` as well.

**Comment by timschumi** [comment]
For now, I'll probably limit myself to testing the different alpine boxes on their newest revisions while overriding the box type to `:linux` in my application's Vagrantfile. Right now, it seems to look even worse already than originally documented in the GitHub Issue (hashicorp/vagrant#10584), since the box fails to do the initial network provisioning due to a missing capability.

```==> default: Configuring and enabling network interfaces...
Vagrant attempted to execute the capability 'configure_networks'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.```

**Comment by ladar** [comment]
I think you stumbled upon why I decided to force the `:alt` guest type by default. It was a workaround for that issue.

It's been almost 2 years since I had to troubleshoot the issue, and found the workaround, but as I recall, the `:linux` type assumed that certain commands and/or config files would be availabl and of course Alpine broke those rules. Hence the fatal failure. I forget why the `:alt` type worked. But it's also why I [proposed creating a `:generic` guest type](https://github.com/hashicorp/vagrant/issues/10701). The plan was to create a standardized command line interface, that `vagrant` could call, and an embedded tool (aka really big and complicated `bash` script) could then translate the config params passed to it, into whatever steps needed to be done for that particular OS. 

In the short term, it might be possible to do the reverse. That is embed the tools `vagrant` needs, or if those commands/tools aren't available, fake them using `bash` scripts. I do that for the `lsb_release` command on Alpine already, since last I checked, there was no package to provide that tool.

As you can see, setting the type to `:alt` was the much easier workaround.
