### ISSUE TITLE
Buster broken

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#58]
Now that Debian v10 Buster has graduated from testing to stable, the repository URLs have changed. This means the generic/debian10 VM is in a corrupt `apt` state, unable to install packages. Let's point the buster VM's at the sharp teeth, unleashed, ultra-beast stable release!

**Comment by ladar** [comment]
I updated the various templates to use the freshly released Debian 10 install media, and I'm rebuilding the Debian 10 images for VMWare, Virtualbox and libvirt as an interim (1.9.19) release since I just finished releasing 1.9.18 a few days ago. 

I don't have remote access to Hyper-V/Parallels build bots at the moment, so those images will need to wait awhile...

If these new images (aka v1.9.19) are still broken, please reopen this issue, and let me know.

**Comment by Yivan** [comment]
@mcandre 
To make apt work on this 1.9.18 you can add in your provisionning script:
`apt-get --allow-releaseinfo-change update`

It worked for me (i am waiting for HyperV release, our work team use HyperV so they can swith easily between Docker for Windows and Vagrant without the need of rebooting - aka virtualbox need to disable hyperv and reboot).
