### ISSUE TITLE
UTC

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#64]
When specifying timezones, please select UTC, which will result in more predictable behavior on our servers.

**Comment by ladar** [comment]
My original configs used CT, since that's where I'm based. I eventually switched to PT, thinking it was the more popular choice. But my newest configs, try to use UTC/GMT. I just haven't gone back and updated/audited all 40 configs.

If there is a universal method of setting the timezone, we could add a common `timezone.sh` config module that does this? Or if it's distro specific (which it is now), add a dedicated `timezone.sh` config.

**Comment by ladar** [comment]
I meant to say, either common `timezone.sh` module, or a distro specific `timezone.sh` config module (aka script) that does this.

**Comment by mcandre** [comment]
timedatectl is common for Linux:

https://coreos.com/os/docs/latest/configuring-date-and-timezone.html#recommended-utc-time

Other operating systems may offer different methods for configuring timezones.

**Comment by ladar** [comment]
@mcandre thank you. Can I assume `timedatectl` is on all of the `systemd` distros? That should cover about half of the roboxes.

I think the SYSV systems can use `tzselect` or `hwclock` but I'm not sure. I've only had to change the system timezone after install via a command line a couple of times, so the  I need to research syntax the process/syntax before attempting any script writing.

Any clue what the different BSDs use?

**Comment by viq** [comment]
Quick and brutal way that should work everywhere is `ln -sf /usr/share/zoneinfo/UTC /etc/localtime`

**Comment by ladar** [comment]
I added a common script to all machines that will try and setup the link if both files exist, where they're expected to be, and of the proper file type. I suspect this might not work on some of the BSD and/or Alpine though.
