### ISSUE TITLE
generic/oracle8: DUID file for DHCP included, cannot start multiple instances on one host

### ISSUE THREAD

**Issue by abbbi** [lavabit/robox#81]
hi,

the generic/oracle8 images seem to include the DUID file for DHCP client. This is an issue if one wants to spin up multiple boxes within one network on the same host. The virtual machines will receive the same ip address from the DHCP server because the DUID of the DHCP client is the same in each box (or they will battle each other with dhcp server to receive it) this will of course lead to network problems.

Other images or boxes make sure the DUID file is removed during build, such that these problems not occur.

Spinning up the oracle8 box on different hosts makes it clear, both of the boxes have the same DUID (outpt from virsh net-dhcp-leases)

box on host1:
192.168.28.185/24         oracle8         ff:5f:6d:aa:a8:00:02:00:00:ab:11:1e:57:af:a9:0c:00:ab:f7
box on host2:
192.168.28.52/24          oracle8         ff:5f:6d:aa:a8:00:02:00:00:ab:11:1e:57:af:a9:0c:00:ab:f7

-> DUID is the same on both hosts, should be different.
I guess rhel8 images have the same problem or here build make sure the duid file was removed.

**Comment by abbbi** [comment]
Without having had a detailed look it seems the build process for libvirt based boxes does not remove or truncate /etc/machine-id. The docker scripts seem to to so:

https://github.com/lavabit/robox/blob/master/scripts/oracle8/dockerize.sh#L50

DUID is probably the same because the machine-id is not regenerated.

**Comment by ladar** [comment]
All of the `libvirt` machines have their machine id truncated by the `scripts/common/machine.sh` script. It's part of the "common" block. The only reason you found it in the `dockerize.sh` script is because the docker boxes don't go through the same cleanup/shutdown process as the VMs. 

So to clarify, is there another file that needs to be wiped/replaced? Perhaps a UUID in the network config, or DHCP configs? Those should get wiped by the `cleanup.sh` module, but that could have changed between R/C/O 7 and 8.

Or is this simply an issue where the machine id isn't being regenerated properly and an identical empty value is being used?

**Comment by ladar** [comment]
Also, isn't the `virsh` command you showed giving you the MAC addresses? Not the machine ids?

**Comment by abbbi** [comment]
hi,

i can confirm that machine-id file within the box.img is empty:

```
<rescue> cat /sysroot/etc/machine-id 
<rescue> 
```

if i spin up two boxes on the system machine in the same libvirt network it seems both
get the same IP Address and at least one box is not reachable. The virsh command only
shows one lease:

```
virsh # net-dhcp-leases lxc
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2019-08-19 11:04:50  52:54:00:0d:7c:da  ipv4      10.1.1.206/24             oracle8         ff:5f:6d:aa:a8:00:02:00:00:ab:11:1e:57:af:a9:0c:00:ab:f7
```

connecting to the virtual machine using virt-manager i can see that
both spinned up vm's have different machine-ids, so they seem the be
regenerated correctly during boot.

My guess is that the DUID is probably stored in some obscure configuration file
on the system, which i cannot tell.

**Comment by ladar** [comment]
This could be happening in a few places. I can't easily test, so I'm hoping you can help troubleshoot. The first is to explode the actual box file and ensure the IDs aren't embedded in the VM config (and not being reset by the provisioning process). 

I assume the ethernet MAC addresses are different? Because if they're the same that will cause DHCP problems. 

Assuming all those hurdles are cleared, you need to look in the `/etc/sysconfig/` and/or `/etc/sysconfig/network-scripts/` folders for a HW address, or some other param. If we're lucky it will match the values you get back from `virsh`. You also need to check the `/etc/NetworkManager/` folder, and if it exists the `/etc/dhcp*` folder. If the identifier isn't in that directorey, you can look at the config and see where the DHCP client is caching its identifiers. It varies widely, but best guess would be somewhere under `/var/run/`. I'm trying to download/test locally, but the connection here is rather slow.

P.S. @abbi Are you using `lxc` containers or the typical `qemu` runtime?

**Comment by abbbi** [comment]
im using qemu runtime, lxc is just the name of the network here, dont be confused by that.

**Comment by ladar** [comment]
Just saw your screenshot confirming the different MAC addresses. It wasn't visible in my email.

So we're likely looking for something being cached by `dhclient`. A simple `ps -ef` may get us the answer:

```
$ ps -ef | grep dhcli
root      2476  2115  0 11:41 ?        00:00:00 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-wlp3s0.pid -lf /var/lib/NetworkManager/dhclient-7a2fcb34-8262-4b59-9e5e-62bdf2aa351f-wlp3s0.lease -cf /var/lib/NetworkManager/dhclient-wlp3s0.conf wlp3s0
```

**Comment by abbbi** [comment]
it seems network manager saves the CLIENTID here, see screenshot.

http://www.grinser.de/~abi/nm.jpg

**Comment by abbbi** [comment]
I removed the *.lease files from the box.img by using virt-rescue and then spinned up two virtual machines from the modified image just fine. So it seems the .lease files cause the issue. This might be a problem with rhel8 and/or upcoming centos8 too.

System 1:

[root@oracle8 vagrant]# grep CLIENT /var/lib/NetworkManager/*.lease
CLIENTID=ff9317095300020000ab1193aaacea3d0e7e98

System 2:

[root@oracle8 vagrant]# grep CLIENT /var/lib/NetworkManager/*.lease
CLIENTID=ff00b00a1d00020000ab11d5d8b41832c6c94f

**Comment by ladar** [comment]
So it looks like the solution is to add a line which removes the "lease" files in the `cleanup.sh` module.

**Comment by ladar** [comment]
This is probably a rule that a variety of distros would benefit from. Any chance you could check the other ones, so I know which distros to apply it? If it's enough, perhaps a common module that looks for specific folders/file patterns?

**Comment by abbbi** [comment]
can only confirm for rhel 8, the box image does include the .lease file too:

```
<rescue> ls -alh /sysroot/var/lib/NetworkManager/
total 20K
drwx------.  2 0 0  150 May 15 21:49 .
drwxr-xr-x. 30 0 0 4.0K May 15 21:46 ..
-rw-r--r--.  1 0 0  939 May 16 04:41 NetworkManager-intern.conf
-rw-r--r--.  1 0 0   68 May 15 21:49 NetworkManager.state
-rw-r--r--.  1 0 0  209 May 16 04:44 internal-eed1e8ed-9317-4840-8bfe-90aebb15059e-eth0.lease
-rw-r--r--.  1 0 0   61 May 16 04:44 timestamps

```
