### ISSUE TITLE
Update packages in images

### ISSUE THREAD

**Issue by FranklinYu** [lavabit/robox#82]
For example, the box `generic/ubuntu1804` is running on kernel 4.15.0-47 while the latest is 4.15.0-52. There are more than 100 packages to update. I’m using v1.9.20 of the box, released only 23 days ago, so I assume that packages are never updated when updating the box.

**Comment by ladar** [comment]
I update the packages during the box build process, so v1.9.22 which started building this morning should contain those updates. It takes 36 to 72+ hours to build and upload, so the updated images should be live by the end of the week. Sooner if all goes smoothly.

My goal is to rebuild all of the images every ~2 but can sometimes be as long as ~4 weeks. It fluctuates based on resources/time constraints.

Two notes, it can take several days to get all of the images built/released, so that probably explains the large number of updates, as that image is probably ~25 to ~30 days old. You can check `/etc/vagrant_box_build_time` for the actual build time of a specific distro on a specific platform. 

Second note, I've been training a new dev team in India as of late, and don't have access to all my build bots, so the Hyper-V/Parallels images aren't being updated with every release. I wasn't able to set up remotely accessibly build bots for those platforms before leaving, so I've been doing my best to target specific images and rebuild those using the machines I brought with me. But with a 5 megabit connection (at best) it's difficult. Takeaway is the images on those platforms may be older.
