### ISSUE TITLE
generic/ubuntu1804 parallels tools missing in 1.9.32

### ISSUE THREAD

**Issue by gildas** [lavabit/robox#89]
HI,

Seems like the old issue #7 is back. Just downloaded version 1.9.32, produced 2 days ago.
And he Parallels tools are not installed using this provider.

Thanks

**Comment by ladar** [comment]
It's possible a kernel update, or some other change caused that module to break. I haven't looked yet. I updated the boxes which use install the tools via the ISOs to use 5.2.34 with this next release. 

Of course those boxes use the distro packages, then that could be where the problem lies. 

If the forthcoming 1.9.38 boxes still have this issue, let me know, and hopefully how to fix it!

**Comment by ladar** [comment]
P.S. #7 was in regards to the VirtualBox tools. But the issue title says Parallels. Is that a typo? If not see #90 .

**Comment by gildas** [comment]
Let's use #90 only.
