### ISSUE TITLE
More boxes!

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#9]
Hey, thank you for maintaining so many useful Vagrant boxes online, and supporting many backend providers as well! I'd love to see even more guest OS's available through robox! Feel free to crib a few from my packer templates:

https://github.com/mcandre/packer-templates

* Illumos: DilOS, SmartOS
* DragonflyBSD
* HardenedBSD
* macOS
* NetBSD
* Haiku OS
* MINIX
* another musl/Linux with xbps packages: Void Linux
* Windows

**Comment by ladar** [comment]
Hi @mcandre I'd welcome a pull request, if you can shoehorn your templates into the robox build process? DragonFly and NetBSD seem like good candidates to start with?  Windows and Minix are high on my long term wishlist as well, but are more complicated.

MacOS is high on my list as well. I've built a MacOS VM by hand, so I know how painful the process is to acquire/prepare install media, plus configure virtual hardware that will then run MacOS. So as much as I'd like to have MacOS images to test with, the difficulty has kept me away. I'm not even sure MacOS will run on all 5 hypervisors I currently target? I've only been able to MacOS guests running on Parallels and VMWare, and I know at one point VMWare Workstation needed a small patch to boot MacOS... (Containers don't count, since they are Linux only.) Anyways, this is a long winded way of saying I don't have the time to tackle this myself right now... and when I do make the attempt, I'll probably start with Darwin.

If you do want to create a pull request, the job just got a lot easier. I just finished up a script (last night) that allows me to add a new distro to the generic build process with one command... I made it thinking I had a sponsor for the build farm, and I used the script to add FreeBSD 12.0 (Beta 4) to the currently ongoing 1.8.48 build... The ease of adding distros has made it hard to resist the urge to go crazy, but how long it currently takes my army of robots to build what I already have has kept me in check. 

Anyways, if you want to make the attempt, move the `res/scripts/add.sh` script to the repo root (not sure it will run from the subdirectory). It will allow you to 'copy' an existing build configuration... which makes adding distros that are similar pretty easy. I don't know how well the OpenBSD or FreeBSD configs will work for you, but at the very least the stubs will be there for you to copy the necessary commands into. The syntax is simple:

```
./add.sh EXISTING NEW ISO HASH
```

In practical terms, I was able to copy the existing FreeBSD 11 config and create a new FreeBSD 12 target by running:

```
./add.sh freebsd11 freebsd12 https://download.freebsd.org/ftp/releases/ISO-IMAGES/12.0/FreeBSD-12.0-BETA4-amd64-disc1.iso 71357b89569f9ff8b1863126f22d03f20c738dd215ab99fa9be95d1e497758ba
```

Of course you still need to look over the new files, and make sure they're correct,  but it should make shoe horning your templates into the robox process easier.

**Comment by mcandre** [comment]
Oh, by the way, my boot_command for macOS is currently broken, unfortunately! Apple changed their High Sierra / Mojave installation wizard just enough to break the script. I spent a month writing and testing it, grr.

But I hope this provides enough of a template to build a working robox VM for mac!

**Comment by ladar** [comment]
@mcandre I feel your pain. That's why I'm hesitent to add more distros, till I get better build bots. Especially a challenging one like MacOS, which will take probably 30 to 90 minutes for each build attempt... so and with 5 hypervisors, and 4 to 20 attempts to get it right, the time adds up quick! 

I'm already ashamed of how many hours I spent figuring out how to get some of my less cooperative distros to build on Hyper-V. 

I was curious, so I checked I'm currently build v1.4.48, which will generate 359 images (not all of them are Vagrant images... some go to docker, some turn into ovas, etc). Of course I've already had 2 Hyper-V and 2 Parallels builds fail. I'm hoping it is just cosmic rays. But I could be feeling more of the joy you described vary soon.

Like I said, if you want to generate the PR, I'm willing to try adding 2 or 3 of your less challenging targets, to my current build pool. That's why I suggested DragonFly, NetBSD, and MINIX, since they're on my list, and shouldn't be too challenging. (Although the BSDs have struggled on Hyper-V...) 

If you can't put together the PR, I'll get it to eventually, I just don't have the time right now to try adapting the configs for the 1.4.48 build. 

P.S. Devuan is also high on my list.

**Comment by ladar** [comment]
> Ach, could we get NetBSD going at least? That one is a rolling release and frequently gets out of date unless new boxes are regularly built :

@mcandre I already added NetBSD.
