### ISSUE TITLE
centos/8: libvirt box fails to boot

### ISSUE THREAD

**Issue by tomaskrizek** [lavabit/robox#94]
### Description
During the boot process of CentOS 8 libvirt box, there's a device mapper timeout for `dev-mapper-cl_centos8\x2dswap.device`. Afterwards, there's a failure of the `systemd-hibernate-resume` job. Then there are warning about `dracut-initqueue` timeouts, until it eventually starts the dracut emergency shell, instead of booting properly. See attached screenshot for details.

### Screenshots
![log1](https://0x0.st/zxe5.png)
![log2](https://0x0.st/zxeR.png)

### Versions
- box: `roboxes/centos8` (libvirt, 1.9.36)
- vagrant 2.2.5
- libvirt 5.6.0
- vagrant-libvirt 0.0.45

**Comment by ladar** [comment]
At first glance, it looks like a mismatch between the virtual machine config used when the image is created, and what libvirt creates during provisioning. Since the default virtual hardware can change based on your qemu/libvirt version, it would be helpful to know what host you're using?

We have mitigation strategies for issues like this for the older boxes, but CentOS 8 is so new, that I haven't had time to test/develop those, and add them to build process yet. If you figure out how to solve these problems, please let me know.

Do you have the same issue with the roboxes/rhel8 and roboxes/oracle8 images? 

The hibernation error _could_ be a result of having a swap partition that is smaller than the allocated guest memory. I know that if all of the ram can't be saved to the swap parition, you can't hibernate. If that proves to be the case we have a few options to mitigate it.

As for the dracut/boot failure, that could be kernel/driver problem. If your version of qemu is using a different storage system, for example, and that kernel module wasn't included in the kernel image, it can cause problems. Of course I could be way off base here too. 

@akdriveus @tomaskrizek any solutions?

I also know a large number of updates were delayed, including a few kernel updates. They were finally released a few days ago, and should be in the 1.9.38 release I'm currently building. It's possible those updates fix this issue as well.

**Comment by ladar** [comment]
@tomaskrizek can you try adding the following to your `Vagrantfile` and report back please...

```
  config.vm.provider :libvirt do |v, override|
    v.disk_bus = "virtio"
  end
```

**Comment by tomaskrizek** [comment]
Thanks for the suggestion! Using `disk_bus = "virtio"` seems to solve the issue - the `roboxes/centos8` box boots properly.

My host OS is Archlinux and qemu version is 4.1.0.

I don't have this issue with `roboxes/rhel8` and it boots expected without modifying the config.

**Comment by flavio-fernandes** [comment]
I had the same issue and was able to workaround using the suggestion provided by @ladar 
https://github.com/lavabit/robox/issues/94#issuecomment-542979685

Thanks!

**Versions**
* box: generic/centos8      (libvirt, 1.9.36)
* vagrant 2.2.5
* libvirt 4.0.0
* vagrant-libvirt 0.0.45

**Comment by ladar** [comment]
I've updated the bundled Vagrantfile templates for RHEL 8/CentOS 8/Oracle 8 so they all specify `virtio` instead of `scsi`.

All of the other boxes use `scsi`... and it seems to have worked well. Not sure why it doesn't with RHEL 8. I opened a ticket with Red Hat back when 8 was in beta, but I guess it never got solved ... https://bugzilla.redhat.com/show_bug.cgi?id=1662069

I tried testing all the boxes using `virtio` and only about half of them worked that way, so I don't fully understand what's happening, but I opened this ticket...  https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1054 ... so hopefully I'll get some advice on what the best defaults are.
