### ISSUE TITLE
generic/rhel8 Error: Unable to find a match

### ISSUE THREAD

**Issue by akdriveus** [lavabit/robox#98]
Vagrant did not finish the installation of the generic/rhel8 box due to the following error:

"The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel kernel-devel-`uname -r` gcc binutils make perl bzip2

Stdout from the command:

Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Extra Packages for Enterprise Linux 8 - x86_64   11 kB/s |  14 kB     00:01
Extra Packages for Enterprise Linux 8 - x86_64  830 kB/s | 3.3 MB     00:04
Last metadata expiration check: 0:00:01 ago on Wed 06 Nov 2019 07:04:18 PM UTC.
Package kernel-devel-4.18.0-80.el8.x86_64 is already installed.
Package kernel-devel-4.18.0-80.el8.x86_64 is already installed.
Package gcc-8.2.1-3.5.el8.x86_64 is already installed.
Package binutils-2.30-49.el8.x86_64 is already installed.
Package make-1:4.2.1-9.el8.x86_64 is already installed.
No match for argument: perl
Package bzip2-1.0.6-26.el8.x86_64 is already installed.

Stderr from the command:

Error: Unable to find a match"

generic/rhel8 Vagrant box:
https://app.vagrantup.com/generic/boxes/rhel8

**Comment by Honiix** [comment]
Hi,

I have the same problem (Vagrant 2.2.6, vagrant-vbguest 0.22.1 and VirtualBox 6.0.14)

I'm under the impression that this command (yum install -y kernel-devel [...] perl [...]) is launched from vagrant-vbguest because I didn't find it in this repository.
The package "perl" is unavailable until your register the RedHat server.

Strangely this is working for RHEL 7 without registration.

Anyone have come to a solution?

**Comment by ladar** [comment]
@akdriveus if your using the RHEL image, you won't be able to install any new packages until you register the box image.

@Honiix assuming you registered the RHEL image, then I think your attempt is failing because of the new "stream" concept with RHEL 8. For certain packages, like `perl`, `python`, `mariadb`, `java`, etc, you need to pick a "stream" like `perl-5` or `perl-6`. 

Package streams are a distinct concept from "stream" repos. The latter are repos with newer package files, which are still being tested.

You can access streams using the `dnf module` sub-command. Technically, if you're using `yum` it is simply a pass through on RHEL 8.

[This](https://docs.centos.org/en-US/8-docs/managing-userspace-components/assembly_managing-versions-of-appstream-content/) CentOS documentation may help.
